### ISSUE TITLE
usocket-udp is going away

### ISSUE THREAD

**Issue by quicklisp** [nklein/cl-growl#1]
Usocket now supports the udp features previously featured in usocket-udp. The author of usocket-udp wants it removed from quicklisp. Can you update cl-growl to use usocket directly?

**Comment by nklein** [comment]
Indeed.  I will do that.  I can probably get that done by November 6th or 7th.

Thanks...

**Comment by quicklisp** [comment]
Any word on this?

**Comment by nklein** [comment]
Sorry... I totally lost track on that one... I should be able to tackle that this afternoon.

-- Patrick <pat@nklein.com>

**Comment by nklein** [comment]
Corrected in version 1.2.20161206 available now.
